version: '3'

services:
  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
        # POSTGRES_ROOT_PASSWORD: "root"
      POSTGRES_PASSWORD: root
      POSTGRES_DB: user_db
    ports:
      - "5434:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
#    networks:
#      demo_net:
  users-service:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/user_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

    depends_on:
      - postgres-db
#    networks:
#      demo_net:
#        ipv4_address: 172.30.0.2

volumes:
  db-data:
#
#networks:
#  demo_net:
#    external: true
