version: "3"

services:
  microservice:
    restart: always
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - custom_network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: monitor_db
    ports:
      - "5435:5432"
    # networks:
    #   - custom_network

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    # networks:
    #   - custom_network
# networks:
#   custom_network:
#     driver: bridge
